### ISSUE TITLE
Conform to primary key abstraction

### ISSUE THREAD

**Issue by podocarp** [AY1920S1-CS2103T-W11-2/main#109]
In Activity class there is many mentions of ids.contains() for example. That should not be the case. We should clean things up and use the hasPerson method instead.

**Comment by Aulud** [comment]
Should we defer this to refactoring at v1.4? Or just clean it up as we go till the end of v1.3?

**Comment by podocarp** [comment]
I think it can wait till 1.4

**Comment by podocarp** [comment]
Slowly got cleaned up, or so it seems.
