### ISSUE TITLE
Pipe updates to Context from commands to UI

### ISSUE THREAD

**Issue by Aulud** [AY1920S1-CS2103T-W11-2/main#139]
## Pipe updates to Context from Commands to UI
Description:
Presently, the UI for contexts `LIST_ACTIVITY` and `LIST_CONTACT` listens to changes in the associated `List` data and automatically re-renders the entries when structural changes occur.

However, the UI for the remaining two contexts `VIEW_ACTIVITY` and `VIEW_CONTACT` do not have such listeners to their associated data (an `Activity` or `Person`), since the models do not make use of `ObservableValue<T>` (which generates change events for the UI to respond to). Therefore, when a command changes the data of an `Activity` or `Person`, it does not prompt a re-render of the details of that viewed entry, due to their largely immutable nature.

This is a known limitation of the current architecture and the proposed workarounds are:
- Replace all attributes of some type `T` in `Person` and `Activity` models (recursively) with the wrapper `Observable<T>`, to allow deep changes to bubble to the `Observable<Activity | Person>`.
- Pass a reference to the updated instance through in a new `Context` with the same `ContextType` in the `CommandResult` returned to the UI.

**Comment by liakify** [comment]
#129
