### ISSUE TITLE
Remove ID entries in UI

### ISSUE THREAD

**Issue by podocarp** [AY1920S1-CS2103T-W11-2/main#189]
This will prevent #157 #155 type of reports. Security through obscurity. It was mainly meant for debug anyways and none of the commands uses it in their syntax.

**Comment by Aulud** [comment]
Yes, this was left in intentionally for debug purposes in v1.3. When we're absolutely sure the IDs are behaving as intended, I'll wipe those labels off.

**Comment by Aulud** [comment]
Resolved by #206.
