### ISSUE TITLE
Add debug GUI for viewing details of an activity or contact

### ISSUE THREAD

**Issue by liakify** [AY1920S1-CS2103T-W11-2/main#51]

**Comment by podocarp** [comment]
Is this really priority high?

**Comment by Aulud** [comment]
> Is this really priority high?

Practically this whole project is priority high. 🤷‍♂

**Comment by liakify** [comment]
in the end we ended up just waiting for the view command itself to complete 😂

**Comment by Aulud** [comment]
Addressed by PR #124.
