### ISSUE TITLE
Add unique name constraint for contacts

### ISSUE THREAD

**Issue by liakify** [AY1920S1-CS2103T-W11-2/main#52]

**Comment by podocarp** [comment]
It seems to me that the `add` command already checks for unique names?

**Comment by Aulud** [comment]
> It seems to me that the `add` command already checks for unique names?

Yes, the constraint is enforced by the chain of method calls `AddCommand::execute -> ModelManager::hasPerson -> AddressBook::hasPerson -> UniquePersonList::contains -> Person::isSamePerson`.

Issue thus closed.
