### ISSUE TITLE
Add unique IDs to reference activities and contacts

### ISSUE THREAD

**Issue by Aulud** [AY1920S1-CS2103T-W11-2/main#77]
This is required for the View command to be context-less and reference a contact or activity directly to show details of. The alternative would be to allow the View command to be contextual and use the index of the targeted item to select it.

**Comment by podocarp** [comment]
#80 for reference. Contacts already have a primary key.

**Comment by Aulud** [comment]
Partially complete - Activities are still missing a unique ID (primary key). Rollover to milestone v1.3.
