### ISSUE TITLE
As a user, I can delete group activities

### ISSUE THREAD

**Issue by podocarp** [AY1920S1-CS2103T-W11-2/main#8]
so that I can remove activities that are over

**Comment by Aulud** [comment]
Rollover to milestone v1.3. Contextual delete command is planned for v1.3.

**Comment by podocarp** [comment]
@AY1920S1-CS2103T-W11-2/developers Question: does this refer to expenses? Otherwise can close.

**Comment by liakify** [comment]
Deleting an activity should delete the expenses together with it, but I don't think this issue specifically refers to deleting expenses

**Comment by Aulud** [comment]
Addressed by @JohnNzj's PR #196.
